NAMES = {
    "u": "Blue",
    "g": "Green",
    "r": "Red",
    "w": "White",
    "b": "Black",
    "uw": "Azorius",
    "bw": "Orzhov",
    "rw": "Boros",
    "gw": "Selesnya",
    "bu": "Dimir",
    "ru": "Izzet",
    "gu": "Simic",
    "br": "Rakdos",
    "bg": "Golgari",
    "gr": "Gruul",
    "guw": "Bant",
    "grw": "Naya",
    "bru": "Grixis",
    "buw": "Esper",
    "bgr": "Jund",
    "bgu": "Sultai",
    "bgw": "Abzan",
    "ruw": "Jeskai",
    "gru": "Temur",
    "brw": "Mardu",
    "bgru": "Sans White",
    "bgrw": "Sans Blue",
    "bguw": "Sans Red",
    "bruw": "Sans Green",
    "gruw": "Sans Black",
    "bgruw": "5 color"
}
